apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qv7iq1k9c-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qv7iq1k9c-go 
  name: qv7iq1k9c-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qv7iq1k9c-go 
